/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEscalasIndexRouteImport } from './routes/_app/escalas/index'
import { Route as AppEscalasNovaRouteImport } from './routes/_app/escalas/nova'
import { Route as AppEscalasIdRouteImport } from './routes/_app/escalas/$id'
import { Route as AppEscalasIdDiasDataRouteImport } from './routes/_app/escalas/$id.dias.$data'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasIndexRoute = AppEscalasIndexRouteImport.update({
  id: '/escalas/',
  path: '/escalas/',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasNovaRoute = AppEscalasNovaRouteImport.update({
  id: '/escalas/nova',
  path: '/escalas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasIdRoute = AppEscalasIdRouteImport.update({
  id: '/escalas/$id',
  path: '/escalas/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalasIdDiasDataRoute = AppEscalasIdDiasDataRouteImport.update({
  id: '/dias/$data',
  path: '/dias/$data',
  getParentRoute: () => AppEscalasIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/escalas/$id': typeof AppEscalasIdRouteWithChildren
  '/escalas/nova': typeof AppEscalasNovaRoute
  '/escalas/': typeof AppEscalasIndexRoute
  '/escalas/$id/dias/$data': typeof AppEscalasIdDiasDataRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/escalas/$id': typeof AppEscalasIdRouteWithChildren
  '/escalas/nova': typeof AppEscalasNovaRoute
  '/escalas': typeof AppEscalasIndexRoute
  '/escalas/$id/dias/$data': typeof AppEscalasIdDiasDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/escalas/$id': typeof AppEscalasIdRouteWithChildren
  '/_app/escalas/nova': typeof AppEscalasNovaRoute
  '/_app/escalas/': typeof AppEscalasIndexRoute
  '/_app/escalas/$id/dias/$data': typeof AppEscalasIdDiasDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/escalas/$id'
    | '/escalas/nova'
    | '/escalas/'
    | '/escalas/$id/dias/$data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/escalas/$id'
    | '/escalas/nova'
    | '/escalas'
    | '/escalas/$id/dias/$data'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/escalas/$id'
    | '/_app/escalas/nova'
    | '/_app/escalas/'
    | '/_app/escalas/$id/dias/$data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalas/': {
      id: '/_app/escalas/'
      path: '/escalas'
      fullPath: '/escalas/'
      preLoaderRoute: typeof AppEscalasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalas/nova': {
      id: '/_app/escalas/nova'
      path: '/escalas/nova'
      fullPath: '/escalas/nova'
      preLoaderRoute: typeof AppEscalasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalas/$id': {
      id: '/_app/escalas/$id'
      path: '/escalas/$id'
      fullPath: '/escalas/$id'
      preLoaderRoute: typeof AppEscalasIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalas/$id/dias/$data': {
      id: '/_app/escalas/$id/dias/$data'
      path: '/dias/$data'
      fullPath: '/escalas/$id/dias/$data'
      preLoaderRoute: typeof AppEscalasIdDiasDataRouteImport
      parentRoute: typeof AppEscalasIdRoute
    }
  }
}

interface AppEscalasIdRouteChildren {
  AppEscalasIdDiasDataRoute: typeof AppEscalasIdDiasDataRoute
}

const AppEscalasIdRouteChildren: AppEscalasIdRouteChildren = {
  AppEscalasIdDiasDataRoute: AppEscalasIdDiasDataRoute,
}

const AppEscalasIdRouteWithChildren = AppEscalasIdRoute._addFileChildren(
  AppEscalasIdRouteChildren,
)

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEscalasIdRoute: typeof AppEscalasIdRouteWithChildren
  AppEscalasNovaRoute: typeof AppEscalasNovaRoute
  AppEscalasIndexRoute: typeof AppEscalasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEscalasIdRoute: AppEscalasIdRouteWithChildren,
  AppEscalasNovaRoute: AppEscalasNovaRoute,
  AppEscalasIndexRoute: AppEscalasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
